name: CommandLine Project CI

on:
  workflow_dispatch:
    inputs:
      tags:
        default: 'deximy/pdf2epub-cmd:latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Pdf2Epub.CommandLine
          file: ./Pdf2Epub.CommandLine/Dockerfile
          push: true
          tags: ${{ github.event.inputs.tags }}
